spring.application.name=movieAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/movieDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver